name: go
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      max-parallel: 2
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        cgo: ['1', '0']
    # if: ${{ github.ref == 'refs/heads/main' || matrix.os == 'ubuntu-latest' }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - name: install gotestsum
      run: go install gotest.tools/gotestsum@latest

    - name: install sqlc-gen-test
      run: go install github.com/sqlc-dev/sqlc-gen-test@v0.1.0

    - name: install ./...
      run: go install ./...
      env:
        CGO_ENABLED: ${{ matrix.cgo_enabled }}

    - name: build internal/endtoend
      run: go build ./...
      working-directory: internal/endtoend/testdata
      env:
        CGO_ENABLED: ${{ matrix.cgo_enabled }}

    - name: test ./...
      run: gotestsum --junitfile junit.xml -- --tags=examples -timeout 20m ./...
      env:
        CI_SQLC_PROJECT_ID: ${{ secrets.CI_SQLC_PROJECT_ID }}
        CI_SQLC_AUTH_TOKEN: ${{ secrets.CI_SQLC_AUTH_TOKEN }}
        SQLC_AUTH_TOKEN: ${{ secrets.CI_SQLC_AUTH_TOKEN }}
        CGO_ENABLED: ${{ matrix.cgo_enabled }}

  vuln_check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true
    - run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - run: govulncheck ./...
